name: opensong_bible_generator
description: A once-used script to generate missing Hungarian bible translations for OpenSong.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
dependencies:
  html: ^0.15.1
  http: ^0.13.5
  xml: ^6.2.2
